root = "."
tmp_dir = "tmp"

[build]
    bin = "tmp/main"
    args_bin = [ "web" ]
    pre_cmd = ["echo pre_cmd", "cd .."]
    cmd = "templ generate && go build -o ./tmp/main ."
    post_cmd = ["echo post_cmd"]
    delay = 500
    exclude_dir = ["assets", "tmp", "vendor","db"]
    exclude_file = []
    exclude_regex = [".*_templ.go"]
    exclude_unchanged = false
    follow_symlink = false
    full_bin = ""
    include_dir = []
    include_ext = ["go", "tpl", "tmpl", "templ", "html","css"]
    kill_delay = "1s"
    log = "build-errors.log"
    send_interrupt = true
    stop_on_error = true
    rerun = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[proxy]
    app_port = 3000
    enabled = true
[misc]
  clean_on_exit = false
