---

# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - 'main'
      # - '**'

#   pull_request:
#     branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Info
        run: printenv

      - name: GoInfo
        run: go env

      # - name: Setup
      #   run: make setup
      #
      # - name: Run sqlc
      #   run: sqlc generate
      #
      # - name: Run templ
      #   run: templ generate
      #
      # - name: Build
      #   run: go build -v ./...
      #
      # - name: Test
      #   run: go test -v ./...

# --- EOF
